language: perl

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

# Allow Travis to use Docker
sudo: false

script:
    - dzil test --author --release
